# Generated by Django 5.2.1 on 2025-05-20 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoAvaliacao',
            new_name='AvaliacaoTipo',
        ),
        migrations.RenameModel(
            old_name='Instituicao',
            new_name='InstituicaoEnsino',
        ),
        migrations.AlterModelOptions(
            name='instituicaoensino',
            options={'verbose_name': 'Instituição de Ensino', 'verbose_name_plural': 'Instituições de Ensino'},
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='tipo',
            new_name='avaliacao_tipo',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='instituicao',
            new_name='instituicao_ensino',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='instituicao',
            new_name='instituicao_ensino',
        ),
        migrations.CreateModel(
            name='CursoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horária')),
                ('periodo', models.CharField(max_length=20, verbose_name='Período')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Disciplina por Curso',
                'verbose_name_plural': 'Disciplinas por Curso',
            },
        ),
        migrations.DeleteModel(
            name='DisciplinaCurso',
        ),
    ]
