# Generated by Django 5.2.1 on 2025-05-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areasaber',
            options={'verbose_name': 'Área do Saber', 'verbose_name_plural': 'Áreas do Saber'},
        ),
    ]
